"""Initial migration.

Revision ID: 86db3837cbbf
Revises: 
Create Date: 2021-05-13 00:32:07.750347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86db3837cbbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_path')
    # ### end Alembic commands ###
